stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demandcluster/gpt:v1
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
notification: {}
